version: '3.8'

services:
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/src/
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
    networks:
      - weather-net

networks:
  weather-net:
    driver: bridge