version: '3.8'

services:
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    container_name: backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/src/
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
    networks:
      - weather-net

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    container_name: frontend
    stdin_open: true
#    command: npm run start
    volumes:
      - ./frontend:/src/
      - /src/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - weather-net

networks:
  weather-net:
    driver: bridge